README.md, percy/C4_Container Diagram Sample - bigbankplc.puml, percy/C4_Container Diagram Sample - message bus.puml, percy/C4_Container Diagram Sample - techtribesjs.puml, percy/C4_Context Diagram Sample - bigbankplc-landscape.puml, percy/C4_Context Diagram Sample - enterprise.puml
Adds () to LAYOUT_TOP_DOWN() in percy diagrams and removes a comment from the readme diagram examples. I will merge this right away to have a complete master branch
=> Fixes percy diagrams

README.md
#74 Add sample, which describes the differences between Rel_* and Lay_*
=> Add sample rel_* versus lay_*

C4_Dynamic.puml, README.md, samples/C4_Dynamic Diagram Sample - message bus - old format.puml
Instead of the increment() and setIndex() functions the user can use Index(), LastIndex() and SetIndex() directly in the RelIndex(...) macro. (The already existing Increment() and setIndex() functions works unchanged)
The new notation is shorter \(and I think simpler\) like below  
```
Rel_D(customer, app, "Updates his profile using", "HTTPS")
Rel(app, customer_service, "Updates customer information using", "JSON/HTTPS")
Rel_R(customer_service, customer_db, "Stores data in", "JDBC")
RelIndex_D(Index()-1, customer_service, message_bus, "Sends customer update events to", "async")
RelIndex_U(LastIndex()-2, customer_service, app, "Confirm update to", "async")
RelIndex_L(Index()-1, message_bus, reporting_service, "Sends customer update events to", "async")
RelIndex(Index()-1, …
```
=> #96 Dynamic diagrams supports Index(), LastIndex() and SetIndex()

C4.puml
the Rel_() definitions with the default argument $direction=""
```
!unquoted procedure Rel_($alias1, $alias2, $label, $direction="")
!unquoted procedure Rel_($alias1, $alias2, $label, $techn, $direction="")
```
are (details see #124)
1. not working with default values (if $direction is "" an invalid PlantUML syntax is created)
2. if a user uses Rel_() with 4 arguments then it is not clear whether the system uses the first or second definition. (after check. first defintion is used)
Therefore the default values are only missleading and not usable and should be removed.
BR Helmut
=> #124 Remove not working, misleading and unused default values

C4_Context.puml
Added SystemDb and SystemDb_Ext with full style support.
(I use my ...extended... urls that the preview is working)
```
@startuml
System(foo, "Foo")
SystemDb(bar, "Bar")
SystemDb_Ext(bar_ext, "Bar Ext")
Rel(foo, bar, "Baz")
Rel(foo, bar_ext, "Baz")
@enduml
```
This PR should fix #113 
BR Helmut
=> #113: Restore SystemDb and SystemDb_Ext

C4.puml
PlantUML realises all boundaries via packages therefore following package specific skinparams have to be set that the boundaries correspond with the defined `rectangle<<boundary>>` style (techn. text should be not bold and no sterotype should be displayed).
```
skinparam package {
StereotypeFontSize 0
FontStyle plain
}
```
current master branch without bugfix 
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
System_Boundary(c1, "Sample System Boundary") {
System(twitter, "Twitter")
}
System_Boundary(c2, "Sample System2 Boundary") {
}
@enduml
```
my local branch with bugfix
```
@startuml
System_Boundary(c1, "Sample System Boundary") { …
```
=> #128: Some boundary skinparam have to be set a package skinparams too

C4.puml
Hi,
I update the boundary skinparams, ... the 0 size should be fixed (new size 6) and the stereotypetext is drawn with the backgroundcolor (==remains invisible)
It can be tested via my [extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended)
```
@startuml
!$COLOR_A_5 = "#7f3b08"
!$COLOR_A_4 = "#b35806"
!$COLOR_A_3 = "#e08214"
!$COLOR_A_2 = "#fdb863"
!$COLOR_A_1 = "#fee0b6"
!$COLOR_NEUTRAL = "#f7f7f7"
!$COLOR_B_1 = "#d8daeb"
!$COLOR_B_2 = "#b2abd2"
!$COLOR_B_3 = "#8073ac"
!$COLOR_B_4 = "#542788"
!$COLOR_B_5 = "#2d004b"
' master doesn't have the new method names
' UpdateSkinparamsAndLegendEntry("boundary", $bgColor=$COLOR_A_5, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_A_1, …
```
=> #133, #48: fix StereotypeFontSize 0 and StereotypeFontColor problem

C4.puml, C4_Context.puml, LayoutOptions.md, README.md, percy/TestPersonPortrait.puml
Additional to SHOW_PERSON_PORTRAIT() the docu of the relationship specific sprites is updated
===========================
- **SHOW_PERSON_PORTRAIT()**: activates portrait outline instead of a rectangle
Based on the new available features a new PR will be created (it replaces #49)
```csharp
@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
!include ./../C4_Deployment.puml
!else
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Deployment.puml
!endif
!$COLOR_A_5 = "#7f3b08"
!$COLOR_A_1 = "#fee0b6"
!$COLOR_NEUTRAL = "#f7f7f7"
UpdateElementStyle("person", $bgColor=$COLOR_A_5, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_A_1, $shadowing="true")
SHOW_PERSON_PORTRAIT()
' default …
```
=> #49, #139: Persons can be displayed as portraits - SHOW_PERSON_PORTRAIT()

README.md
=> Fix typos in project README file

C4.puml, C4_Dynamic.puml, LayoutOptions.md, README.md, percy/TestLayoutLandscape.puml, percy/TestLayoutLandscapeDynamic.puml
This PR solves the #174 issue.
`LAYOUT_LEFT_RIGHT()` rotates the default flow direction and the directed relations rotates, e.g. `Rel_Right()` is displayed as relation from up to down, like below
```plantuml
@startuml
LAYOUT_LEFT_RIGHT()
Person(admin, "Administrator")
System_Boundary(c1, 'Sample') {
Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")
Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
System(S,"S")
System(SU,"S Up")
System(SD,"S Down")
System(SL,"S Left")
System(SR,"S Right")
Rel_Up(S, SU, "Up")
Rel_Down(S, SD, "Down")
Rel_Left(S, SL, "Left") …
```
=> #174 Add LAYOUT_LANDSCAPE()

LayoutOptions.md, README.md
fixed #184, no red blocks are displayed in code samples anymore. It can be checked via [kirchsth/extended](https://github.com/kirchsth/C4-PlantUML/tree/extended)
e.g.
```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Context.puml
Person(user, "User")
Person(user1, "User 1")
Person(user2, "User 2")
Person(user3, "User 3")
System(system, "System")
' normal sprites are too big 
Rel_L(user, user2, "informs", "courier", "normal sprites are too big", $sprite="person2")
' scaled sprites are ok
Rel_R(user, user3, "informs", "courier", "scaled sprites are OK", $sprite="person2,scale=0.5")
' combine sprite and scale to a new sprite
!$combinedSprite="person2,scale=0.5"
Rel_R(user, user3, "informs", "courier", "combined sprites are OK", …
```
=> #184 code in markdown use plantuml syntax

C4.puml, README.md
Implementation of https://github.com/plantuml-stdlib/C4-PlantUML/issues/211
Properties can be added to relationship too like below
```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Deployment.puml
' default header Property, Value
AddProperty("Name", "Flash")
AddProperty("Organization", "Zootopia")
AddProperty("Tool", "Internet Explorer 7.0")
Person(personAlias, "Label", "Optional Description (with default property header)")
SetPropertyHeader("Property","Value", "Description")
AddProperty("Prop1", "Value1", "Details1")
AddProperty("Prop2", "Value2", "Details2")
Deployment_Node_L(nodeAlias, "Label", "Optional Type", "Optional Description (with custom property header)") {
WithoutPropertyHeader()
AddProperty("PropC1", "ValueC1") …
```
=> #211 AddProperty for relationships

C4.puml, LayoutOptions.md, README.md, percy/TestSketchStyle.puml
Implementation of #186
LAYOUT_AS_SKETCH() styles and the footer text can be changed with SET_SKETCH_STYLE():
* `SET_SKETCH_STYLE(?bgColor, ?fontColor, ?warningColor, ?fontName, ?footerWarning, ?footerText)`:
Enables the modification of differnt sketch styles and footer.
The possible font name(s) depend on the output format (e.g. PNG uses fonts which are installed on the server and SVG fonts have to be installed on the client).
Additional is it possible to define comma separated fall back fonts (if the diagrams are exported as SVG. Atm
PNG does not support fallback fonts based on a PlantUML [bug](https://forum.plantuml.net/14842/specify-fall-back-fonts-is-not-working), but this could be fixed in one of the following versions)
```plantuml
@startuml LAYOUT_AS_SKETCH Sample
!include …
```
=> #186 Change SKETCH layout via SET_SKETCH_STYLE (incl. fonts, color,....)

C4.puml, README.md, percy/TestLayDirections.puml
Implementation of https://github.com/plantuml-stdlib/C4-PlantUML/issues/215
"long" layout calls (`Lay_Up`, `Lay_Right`, `Lay_Down` and `Lay_Left`) can be used like below
```plantuml
@startuml
HIDE_STEREOTYPE()
Person(a, "A")
Person(b, "B")
Person(c, "C")
Person(d, "D")
Person(e, "E")
Lay_U(a, b)
Lay_R(a, c)
Lay_D(a, d)
Lay_L(a, e)
Person(x, "X")
System(s1, "S1")
System(s2, "S2")
System(s3, "S3")
System(s4, "S4")
Lay_Up(x, s1)
Lay_Right(x, s2)
Lay_Down(x, s3)
Lay_Left(x, s4)
@enduml
```
It can be tested with [my extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended)
BR Helmut
PS.: I didn't add something to LayoutOptions.md because I think it is not an option
=> #215 Lay_x calls supports long version Lay_xxxx too

C4_Component.puml, C4_Container.puml, README.md
This change makes the `techn` argument to `Container` and friends optional, similar to how it is optional in `Rel`.
I am not very familiar with this project or plantuml in general, so please review carefully.
=> Make Container techn optional

README.md
* "Sprites and other images" section is added to Readme.md with a description of all 3 sprite sources
* Relationship section is reordered that "Relationship specific sprites ..." are part of the "Sprites and other images" section
* Sample with BiRel() relationships is added too
* All realtion(s) are renamed to relationship(s)
@Potherca can you please review it (you can check it via [kirchsth/219_UpdateSpriteDocu](https://github.com/kirchsth/C4-PlantUML/tree/feature/219_UpdateSpriteDocu)
Thank you and BR Helmut
....
In following sample a person uses different systems, and a group of persons which have bidirectional relationships
```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()
Person(a, "A")
Person(b, …
```
=> #219 Update Readme.md (add sprite section, a diagram with BiRel() calls and unify relation to relationship)

C4.puml, C4_Component.puml, C4_Container.puml, C4_Context.puml, C4_Deployment.puml, README.md, percy/TestBoundaryTagSupport.puml
implementation of #227
With following calls is it possible to update existing boundary styles or add new boundary tags, which can then be used in combination with the boundaries. (There was already a tag support but now it has a better legend support and it has its own tag namespace that elements and boundaries can have different style for the same tag name)
* `AddBoundaryTag(tagStereo, ?bgColor, ?fontColor, ?borderColor, ?shadowing, ?shape, ?type, ?legendText)`:
Introduces a new Boundary tag. The styles of the tagged boundaries are updated and the tag is displayed in the calculated legend.
* `UpdateBoundaryStyle(?elementName, ?bgColor, ?fontColor, ?borderColor, ?shadowing, ?shape, ?type, ?legendText)`:
This call updates the default style of the existing boundaries and creates no …
=> #227 Boundaries can be styled via tags

LayoutOptions.md
Add documentation about layout guidance a practices learned in #237 
Closes #237
=> First draft layout guidance and practices

.github/workflows/run-percy-tests.yml
Currently, the build is broken. This has to do with Percy migrating to a new package structure.
In order to fix the build, instead of using `percy`, `@percy/cli` needs to be used.
This MR does that.
=> Change percy workflow to use @percy/cli.

C4_Component.puml
Use $COMPONENT_FONT_COLOR as the default $fontColor for AddComponentTag and AddExternalComponentTag. Otherwise, tagged components have an unexpected (non-default) font color even when no font color was passed to AddComponentTag.
=> AddComponentTag uses component font by default

LayoutOptions.md, README.md
related to #221
Until we have a split/reorganized documentation a level 3 TOC enables simpler references of sub sections in the documents.
Therefore all **bold marked lines** are converted into H3 headings.
It can be tested with [my extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended/)
* https://github.com/kirchsth/C4-PlantUML/blob/extended/README.md
* https://github.com/kirchsth/C4-PlantUML/blob/extended/README.md#element-specific-tag-definitions
* https://github.com/kirchsth/C4-PlantUML/blob/extended/LayoutOptions.md
* https://github.com/kirchsth/C4-PlantUML/blob/extended/LayoutOptions.md#overall-guidance
BR Helmut
=> Update TOC with level 3 (README.md and LayoutOptions.md)

C4.puml, C4_Component.puml, C4_Container.puml, C4_Context.puml, C4_Deployment.puml, percy/TestLegend.puml
implementation of #247
This fix produces the correct dynamic legend if
- person sprites are defined via SHOW_PERSON_SPRITE() and other PERSON related layout calls 
- multiple UpdateElementStyle() defines the same element type (missing parameters a reused from last call)
- Add....Tag() calls reused the UpdateElementStyle() parameters
(e.g. if an UpdateElementStyle("external_system", ....) calls defines a new background color, a following AddExternalSystemTag() call reused automatically the new defined background color too)
- (C4Version() is updated to *.beta2)
(the sample is logically not useful, but it should show all fixes)
```
@startuml
' person legend displays the correct sprite …
```
=> #247 Element styles are correct combined and dynamic legend is correct calculated

README.md
=> fixing markdown end code indicator

C4.puml, README.md, percy/TestLegend.puml, percy/TestRelationsTags.puml
based on PR #218 from @netrounds-fredrik  and PR #235 from @fredde-fisk. Thank you for your preparatory work.
`AddRelTag()` is extended with a new $lineThickness argument, like `AddRelTag("tag1", $lineThickness=3)`
```plantuml
@startuml
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
AddRelTag("tag1", $lineThickness=3)
AddRelTag("tag2", $lineColor="darkblue", $lineStyle=DottedLine(), $lineThickness=8)
Container(a, "A")
Container(b, "B")
Container(c, "C")
Rel(a, c, "normal")
Rel(a, b, "thickness 3", $tags="tag1")
Rel(b, c, "blue, dotted, thickness 8", $tags="tag2")
SHOW_LEGEND()
@enduml
```
It can be tested with [my extended …
=> Add support for lineThickness in AddRelTag (based on #218, #235)

C4.puml, LayoutOptions.md, README.md, percy/TestLegendDetailsNone.puml, percy/TestLegendDetailsNormal.puml, percy/TestLegendDetailsSmall.puml
implementation of #232
Idea:
- Legend text of a tag definition consists of a label and the \(display\) details.
- If details are displayed with a smaller font then the whole legend gets smaller.
- If $legendText of a tag definition contains a `\n` then the first part defines the label and the second part the details.
- (the first planed idea with pictograms is discarded, I found no useful images)
Realization:
- `SHOW_LEGEND(?hideStereotype, ?details)` and `SHOW_FLOATING_LEGEND(?alias, ?hideStereotype, ?details)` is extended with `?details`: 
- `$details = Small()` .. default; details are displayed with a smaller size compared to the legend labels
- `$details = Normal()` .. details and labels are displayed with same size
- `$details = None()` .. only the labels are displayed
```plantuml …
```
=> #232 Legend details can be smaller or hidden

C4.puml, C4_Component.puml, C4_Container.puml, C4_Context.puml, C4_Deployment.puml, C4_Dynamic.puml, percy/TestLabelsWithLineBreak.puml
implement #255
All `$labels` and missing `$techn` args support line breaks too (I think now we cover all with \n).
It can be tested with [my extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended)
```plantuml
@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="./.." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
!include %get_variable_value("RELATIVE_INCLUDE")/C4_Component.puml
!include %get_variable_value("RELATIVE_INCLUDE")/C4_Deployment.puml
!else
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Deployment.puml
!endif
Enterprise_Boundary(eb, "Enterprise\nBoundary") {
Person(p1, "Normal\nUser\nLabel", …
```
=> #255 All $label  and $techn supports line breaks

LayoutOptions.md, README.md, samples/C4CoreDiagrams.md
If a user opens https://plantuml-stdlib.github.io/C4-PlantUML/ he has no (direct) links to the other *.md files.
Therefore TOC of all deployed *.md files are updated that they can be accessed via https://plantuml-stdlib.github.io/C4-PlantUML/ too
It looks like 
- [:page_facing_up: C4-PlantUML](#c4-plantuml)
- [Getting Started](#getting-started)
- ...
- [:page_facing_up: Layout Options](LayoutOptions.md#layout-options)
- samples
- [:page_facing_up: Core Diagrams](samples/C4CoreDiagrams.md#c4-model-diagrams)
It can be checked with [my extended branch](https://github.com/kirchsth/C4-PlantUML/blob/extended/README.md#c4-plantuml)
@Potherca: During tests I found in README.md some implicit links to LayoutOptions.md and one explicit to C4CoreDiagrams.md. If you want we could reject the PR too.
BR …
=> Extend TOC with links to other files too

C4.puml, C4_Context.puml
implement #256 old version plantuml.jar workaround (details see there)
following samples works now with older versions too
```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
Person_Ext(A, "Person A")
SHOW_LEGEND(true)
@enduml
```
```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Context.puml
UpdateElementStyle("person","orange","green","blue", $legendText="Person\ngreen label is only used in legend")
UpdateElementStyle("external_person","gold", "red", "darkred")
' SHOW_PERSON_OUTLINE()
SHOW_PERSON_PORTRAIT()
Person(p, "A person with orange label")
Person_Ext(extP, "An external person with gold label")
SHOW_LEGEND(false)
@enduml
```
@chriskn can you please test it with [my …
=> #256 Person outline and portrait styles works with old plantuml.jar versions too

.gitattributes
@Potherca: GitHub Linguistic default settings ignores PlantUML as a programming language; following settings should activate it
=> Activate GitHub repository language

percy/C4_Container Diagram Sample - bigbankplc-styles.puml
Fix `cutomer` typo as reported in #279
=> Fix typo in bigbankplc-styles.puml Sample

C4.puml, C4_Component.puml, C4_Container.puml, C4_Context.puml, percy/TestEmptyLabel.puml
implement https://github.com/plantuml-stdlib/C4-PlantUML/issues/281
a) If an element (person, system, component, container) has a $sprite and an empty label then only the $sprite is displayed
b1) If a relationship has a $sprite and a $link, then the link can be activated via the sprite too
b2) If a relationship has an empty label  and a $link the link url is displayed (otherwise nothing can be activated)
b3) If a relationship has an empty label  without a $link the the relationship is displayed without a label
```plantuml
@startuml
LAYOUT_TOP_DOWN()
!$img="img:https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Test-Logo.svg/80px-Test-Logo.svg.png" …
```
=> #281 Sprite with empty labels produces no additional empty new line/space

C4_Context.puml, C4_Deployment.puml, README.md, percy/TestSystemPersonSupportType.puml
close #287
**C4 Model extension:** Person() and System() support `$type` argument too. 
Is uses the same notation as `$techn`, e.g. `$type="characteristic A"` is displayed as `[characteristic A]`
Following macros are extended with the optional argument $type:
- AddPersonTag(), AddExternalPersonTag(), AddSystemTag(), AddExternalSystemTag() is extended with $type as last argument.
- Person(), System(),... is extended with $type as last argument.
- cleanup of AddNodeTag() that it can use $type like in the Node() call itself.
```plantuml
@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="./.." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
!include %get_variable_value("RELATIVE_INCLUDE")/C4_Container.puml
!else
!include …
```
=> #287 System and person support [...] notation

C4.puml
fix #300 `Add....Tag()` related calls do not overwrite the default values anymore
```plantuml
@startuml
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
AddContainerTag(my_Container_tag_1, $bgColor=lightyellow, $fontColor=black, $legendText="This should have new styles")
AddContainerTag(my_Container_tag_2, $legendText="This should have default styles")
Container(regularContainer, Regular Container)
Container(taggedContainer1, Tagged Container With New Styles, $tags=my_Container_tag_1)
Container(taggedContainer2, Tagged Container With DefaultStyles, $tags=my_Container_tag_2)
AddSystemTag(my_System_tag_1, $bgColor=red, $fontColor=darkred, …
```
=> #300 Fix all Add....Tag() related calls

C4.puml, C4_Component.puml, C4_Container.puml, C4_Context.puml, C4_Sequence.puml, README.md, Themes.md, percy/C4_Sequence Diagram Sample - bigbankplc.puml, percy/TestSequenceSkinparams.puml, samples/C4CoreDiagrams.md, samples/C4_Sequence Diagram Sample - bigbankplc.puml, samples/C4_Sequence Diagram Sample - complex.puml, themes/puml-theme-C4_FirstTest.puml, themes/puml-theme-C4_blue.puml, themes/puml-theme-C4_brown.puml, themes/puml-theme-C4_sandstone.puml, themes/puml-theme-C4_superhero.puml, themes/puml-theme-C4_united.puml, themes/puml-theme-C4_violet.puml
related to https://github.com/plantuml-stdlib/C4-PlantUML/issues/307
In the final solutions the sequence diagram supports descriptions, line breaks, links, ... of all elements.
The only main difference are
a) **boundaries have to be defined without `{` and `}`** and instead of `}` the **`Boundary_End()`** macro has to be called
b) descriptions of the elements (person, system,... ) are deactivated; they can be activated via the layout option `SHOW_ELEMENT_DESCRIPTIONS(?show)`
c) in contrast to a normal sequence diagram the foot boxes are deactivated; they can be activated via `SHOW_FOOT_BOXES(?show)`
The C4 language itself is basically not extended, missing new features like [Grouping messages](https://plantuml.com/sequence-diagram#425ba4350c02142c) have to added with native PlantUML …
=> Add (C4 styled) Sequence Diagram support 

.scripts/transform_files.py, C4.puml
Update version with first beta of v2.8.0 (v2.7.0 was created based on previous commit)
additional fixes it some minor comment/findings in the release script
the https://github.com/plantuml/plantuml-stdlib/pull/81 is created too
@Potherca can you please approve it.
=> Update version with first beta of v2.8.0

C4.puml, C4_Component.puml, C4_Container.puml, C4_Context.puml, C4_Deployment.puml, README.md
related to https://github.com/plantuml-stdlib/C4-PlantUML/issues/315
All element and boundary specific tags support $borderStyle and $borderThickness arguments (like the relationships with $lineStyle and $lineThickness).
```plantuml
UpdateElementStyle(...,?borderStyle, ?borderThickness)
AddElementTag(...,?borderStyle, ?borderThickness)
UpdateBoundaryStyle(...,?borderStyle, ?borderThickness)
AddBoundaryTag(...,?borderStyle, ?borderThickness)
```
All element and boundary specific `Add...Tag(...,?borderStyle, ?borderThickness)`or `Update...Style(...,?borderStyle, ?borderThickness)` calls (like `AddPersonTag()` or `UpdateEnterpriseBoundaryStyle()`) are extended too.
Additional a new border style `SolidLine()` is supported and can be used as `$lineStyle= SolidLine()` or …
=> Adjust thickness and styles of element and boundary borders

C4_Dynamic.puml, C4_Sequence.puml
related to #320 
fix overwrites the already existing (C4.puml specific) Rel...() definitions in C4_Dynamic.puml and C4_Sequence.puml too.
Based on that PlantUML resolves all Rel...() deterministic with one of the correct implementations.
It can be tested with my external branch, like below 
```plantuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
```
[![](http://www.plantuml.com/plantuml/svg/RP51QuGm58Jl_ehKoxw5L2yzzRHOZnQAPQ7jPSacwIPKNoG-sIwb_xsl7hJL5Hp6cJ1yn5rFAjBGDicDHzqCnWf7rFNtUHxLEJjvSiDnw6tK0SaYPJgq-OUFslNayeUxswT68UqVgzn-Sc-iuV1GNb2rNcVTxt1IX06DYXTGKcnA7wqc7r2aQMsRDDrilnB13tySod16c9mKuaNoiUtKxpkO7BUhllOdHp0vkUmh-qumkNd_-m_ayHgaU7OXabDe_k72g5AyBZ1Xr5LUmwYhl89HEL_ZQCRXE_Op2aEmB_poze1VATxcwV4853xEEK_lB1h-BJy0)](http://www.plantuml.com/p …
=> #320 Dynamic/Sequence fix Rel() without $index argument

C4.puml
https://github.com/plantuml-stdlib/C4-PlantUML/issues/323
=> fix a001 error

C4.puml
related to #323 and #324
$BOLD_LINE, $SOLID_LINE are constants which cannot be changed via customer specific themes like $DOTTED_LINE and $DASHED_LINE therefore use global definition like $DOTTED_LINE.
=> fix a001 error (2)

C4.puml, C4_Deployment.puml, percy/TestAllAddTags.puml
related to #334
* AddNodeTag() is fixed that it can be used like all other Add*Tag() calls.
* SHOW_FLOATING_LEGEND() is fixed that default size of details is small.
```plantuml
@startuml 
!include http://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Deployment.puml
AddNodeTag("nodeTag", $borderColor="orange", $borderThickness="3")
Boundary(b5, "Boundary 5") {
Node(node, "Node", "Type", "Optional Description", $tags="nodeTag")
Node(node2, "Node2", "Type", "Optional Description")
}
SHOW_FLOATING_LEGEND()
@enduml
```
It can be tested via my [extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended)
[wemu](https://github.com/wemu) can you please test it.
(atm it looks the the online server has sometimes problems with include, if this is the case please test it with …
=> fix AddNodeTag() call + SHOW_FLOATING_LEGEND() uses small details as default 

.github/workflows/run-percy-tests.yml
fix build warning: "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ts-graphviz/setup-graphviz@v1"
=> fix deprecated task in build: update to ts-graphviz/setup-graphviz@v2

C4.puml, C4_Container.puml, C4_Context.puml, C4_Sequence.puml, README.md, percy/TestBoundaryTagSupport.puml, percy/TestSequenceSkinparams.puml
related to #350
All boundaries are extended that they support descriptions too:
- Boundary(..., ?descr)
- Enterprise_Boundary(..., ?descr)
- System_Boundary(..., ?descr)
- Container_Boundary(..., ?descr)
and sprites which are defined via tags 
(If a sprite is defined then it displayed in the first line in front of the label with a smaller size.
The sprite is written in front of the label that the height of the boundary is reduced.)
- AddBoundaryTag(..., ?sprite, ?legendSprite)
- UpdateBoundaryStyle(..., ?sprite, ?legendSprite)
- UpdateContainerBoundaryStyle(..., ?sprite, ?legendSprite)
- UpdateSystemBoundaryStyle(..., ?sprite, ?legendSprite)
- UpdateEnterpriseBoundaryStyle(..., ?sprite, ?legendSprite)
- Default sprite size can be changed via $BOUNDARY_IMAGE_SIZE_FACTOR
The new features …
=> #350 All boundaries supports descriptions and sprites too 

C4.puml, README.md, percy/TestProperty.puml
related to #355
SetPropertyHeader() and AddProperty() are updated that only 1 column is required (the old implementation required at least 2 columns)
- `SetPropertyHeader(col1Name, ?col2Name, ?col3Name, ?col4Name)`
- `AddProperty(col1, ?col2, ?col3, ?col4)`
[![](https://www.plantuml.com/plantuml/svg/ROn1IqCn383lxrVKdjv0LnHFdZRSmSF4mT2J85qRzeffMf8KVV_URhZRJidt9NmhKS_QCWutYGAs26PIhVBa7FkVvJ7fr0vDW4CX1T9bADbz9mwJwEIU7-zsw4dVNxSEVlizGkpoQmCLovnF__NK7lQWEouLMESNy15uj1UsYs4TuuL6--6nmVrL-z3jVXQ5FCfvh35vkJLswm-0jYzlLLCXZsO34ZYTwPD6INH4CA5WosJgVtNHSyCAABQCVm00)](https://www.plantuml.com/plantuml/uml/ROn1IqCn383lxrVKdjv0LnHFdZRSmSF4mT2J85qRzeffMf8KVV_URhZRJidt9NmhKS_QCWutYGAs26PIhVBa7FkVvJ7fr0vDW4CX1T9bADbz9mwJwEIU7-zsw4dVNxSEVlizGkpoQmCLovnF__NK7lQWEouLMESNy15uj1UsYs4TuuL6--6nmVrL-z3jVXQ5FCfvh35vkJ …
=> #355 Single column property

themes/puml-theme-C4Language_italian.puml
The correct italian for "legend" is "legenda". "Leggenda" means more or less "mythical narration".
The https://github.com/plantuml/plantuml-stdlib/pull/128 of the "derived" [plantuml-stdlib](https://github.com/plantuml/plantuml-stdlib) has to be merged into the "original" [C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML) too.
=> #379 correct typo in Italian legend title

C4.puml
C4-PlantUML is compatible up to v1.2023.5 (because of the `?=` operator being used).
We can't use JSON notation (i.e. `$versionPart[1]`) as that triggers a ClassCastException in versions older than v1.2024.5.
The function `%splitstr()` is safe, as it was added in v1.2022.2
Fixes #396
=> Fix for "Use !option handwritten true" warning
